Experimental support for CRB 15000-12/1.27
ros-industrial/abb_experimental pull request #149
Opened 2024-07-12 09:16 UTC by mmmarcopalma

2024-07-12 09:16 UTC, mmmarcopalma commented
/cc @gonzalocasas

2024-07-12 09:48 UTC, gavanderhoorn commented
Thanks for the PR.

Some high-level comments:

- could you remove all the `desktop.ini` files please?
- could none of the meshes of the other variant be reused?
- please add a `roslaunch` test for the new variant
- please update the description in the manifest with the details about the new variant you added
- and if you'd like: please add yourself as an `author`, seeing as you added a new variant

2024-07-12 10:33 UTC, mmmarcopalma commented
Thanks, I'll follow up on your comments.

> * could none of the meshes of the other variant be reused?
I could re-use 3+3 meshes (links 3-5-6). The ones I uploaded are exact copies of the existing ones.   

I'm not fluent yet in git, apologies for missing on some best-practice.

2024-07-12 11:25 UTC, gavanderhoorn commented
> > * could none of the meshes of the other variant be reused?
> 
> I could re-use 3+3 meshes (links 3-5-6). The ones I uploaded are exact copies of the existing ones.

Ok, so this is perhaps due to me not being clear by what I meant by *reuse*.

A `xacro:macro` can refer to files 'anywhere', so you don't have to copy meshes if they are identical to files for other variants.

Just have your `<mesh filename="..."/>` point to the file you'd like to reuse from the other variant.

No need to copy anything.

2024-07-12 14:03 UTC, mmmarcopalma commented
I added a commit with the requested changes. 
 
> * and if you'd like: please add yourself as an `author`, seeing as you added a new variant
Thanks, I added my name in the Package.xml

2024-08-06 09:00 UTC, mmmarcopalma commented
Hello @gavanderhoorn, is there any news regarding this request? 
Thanks!

2024-08-17 16:29 UTC, gavanderhoorn requested changes
Thanks again for the PR. Holiday period got in the way.

See the inline comments for some things that need to be checked and possibly corrected.

Apart from those, I'm wondering whether there is an issue with the normals of `visual` meshes `link_1.stl` and `link_4.stl`:

![rviz_screenshot_2024_08_17-17_22_27](https://github.com/user-attachments/assets/e396bb06-f7d5-44a5-ba7b-c874bd79cb35)

they appear to be inverted, at least partially.

2024-08-17 16:29 UTC, gavanderhoorn commented on abb_crb15000_support/urdf/crb15000_12_127_macro.xacro
> +      <limit effort="0" lower="${radians(-180)}" upper="${radians(180)}" velocity="${radians(125)}"/>
Could you clarify which specific version of the `12/1.27` you're modelling here? According to the documentation I've found (`Product manual, CRB 15000`, `3HAC077389-001`, `Rev L`), there is an option for +-270 degrees as well:

![image](https://github.com/user-attachments/assets/e067b8e3-ba68-4f0c-bef0-669fae7bd345)

2024-08-17 16:29 UTC, gavanderhoorn commented on abb_crb15000_support/urdf/crb15000_12_127_macro.xacro
> +      <limit effort="0" lower="${radians(-180)}" upper="${radians(180)}" velocity="${radians(200)}"/>
The position limits here seem to be different from the documentation I quoted earlier: `+-180` vs `+-270` degrees.

2024-08-17 16:29 UTC, gavanderhoorn commented on abb_crb15000_support/urdf/crb15000_12_127_macro.xacro
> +      <limit effort="0" lower="${radians(-180)}" upper="${radians(180)}" velocity="${radians(125)}"/>
The joint velocity limit also seems off:

![image](https://github.com/user-attachments/assets/3af25e28-eec6-406a-9600-4e7f2ff47f65)

(this is from the CRB 15000 GoFa 10 & 12 Datasheet (from [here](https://new.abb.com/products/robotics/robots/collaborative-robots/crb-15000)))

Same for joints 2 & 3.

Could you clarify where you found the current limits?

2024-08-18 09:09 UTC, mmmarcopalma commented on abb_crb15000_support/urdf/crb15000_12_127_macro.xacro
> +      <limit effort="0" lower="${radians(-180)}" upper="${radians(180)}" velocity="${radians(125)}"/>
these values were simply not updated from the GoFa 5, my bad.

2024-08-18 09:11 UTC, mmmarcopalma commented on abb_crb15000_support/urdf/crb15000_12_127_macro.xacro
> +      <limit effort="0" lower="${radians(-180)}" upper="${radians(180)}" velocity="${radians(125)}"/>
besides mesh normals, i realiize now link_4 is also not clsoed and has a bunch of non-manifold edges.  
fixing all of this right now.

2024-08-18 09:11 UTC, mmmarcopalma commented on abb_crb15000_support/urdf/crb15000_12_127_macro.xacro
> +      <limit effort="0" lower="${radians(-180)}" upper="${radians(180)}" velocity="${radians(200)}"/>
see previous comment.

2024-08-18 09:32 UTC, mmmarcopalma commented
Committed the requested changes. 
Thanks for supporting!

2024-09-02 14:36 UTC, mmmarcopalma commented
Hello @gavanderhoorn, is there anything else I can do to push this PR? 
Thanks!

2024-09-22 13:17 UTC, gavanderhoorn commented
I've re-enabled CI and added a couple of commits.

I believe this is in an OK state to merge. Thanks again for the PR @mmmarcopalma :+1: 

Let's wait on CI to turn green.

2024-09-22 13:27 UTC, gavanderhoorn approved these changes

2024-09-22 13:27 UTC, gavanderhoorn commented
To prevent all the fixups from ending up in the commit history, I'll squash-merge this.

Provenance and attribution will be retained, of course.

2024-09-22 13:28 UTC, merged

2024-09-22 13:28 UTC, gavanderhoorn commented
Thanks again @mmmarcopalma :+1:

2024-09-23 07:24 UTC, mmmarcopalma commented
Great news, thanks for the support @gavanderhoorn!